# Dependencies
markdown:         kramdown

# Permalinks
permalink: /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:            Beer, Battles, and Barbeque
tagline:          'An Americana Adventure'
description:      'On a mission to visit the best breweries and barbeque joints. Battle sites are a bonus.'
baseurl: "/3Bs" # If you are making a gh-pages project blog, this is
                        # the name of your project repo, preceded by a /'
                        # Set it to just "/" if you are making a user page.
                        
                        # That trailing slash is important for proper storage
                        # of figures gnerated from knitting.
baseurlknitr:  "/3Bs/" # This will always be your baseurl plus an extra '/'
                                # at the end.  It's used only when knitr renders
                                # your R Markdown files.
                        
url: "https://natebyers.github.io/3Bs" # the base hostname & protocol for your site

# set limit on number of post to appear on Home page
homepostlimit: 4

# Disqus comments:
disqus:           true
shortname:        natebyers3bs

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post

author:
  name:           'Nathan Byers'
  url:            https://www.linkedin.com/in/nathan-byers-8a64a24

github:
  repo:           https://github.com/NateByers/3Bs/tree/gh-pages
